services:
  - type: web
    name: boss-analysis-tw
    env: python
    plan: free

    buildCommand: pip install -r requirements.txt

    startCommand: gunicorn boss_analysis_tw:app --bind 0.0.0.0:$PORT

    envVars:
      - key: OPENAI_API_KEY
        value: ${OPENAI_API_KEY}
      - key: SMTP_PASSWORD
        value: ${SMTP_PASSWORD}
